table Sales
  lineageTag: simulated-sales

  column OrderId
    dataType: string
    sourceColumn: order_id

  column LocationId
    dataType: string
    sourceColumn: location_id

  column Daypart
    dataType: string
    sourceColumn: daypart

  column Revenue
    dataType: decimal
    formatString: $#,0.00
    sourceColumn: revenue

  column RevenueBand = IF([Revenue] >= 1000, "High", "Standard")
    dataType: string

  measure 'Total Revenue' = SUM(Sales[Revenue])
    formatString: $#,0.00

  hierarchy Location
    level LocationId
      column: LocationId

  partition Sales = m
    mode: import
    source =
      let
        Source = Warehouse,
        SalesTable = Source{[Schema="GOLD",Item="SALES"]}[Data]
      in
        SalesTable
