import type { MigrationBiSourceTool } from './types';

export interface MigrationSourceDocumentationReference {
  title: string;
  url: string;
  authority: string;
  artifactClasses: string[];
  reviewedAt: string;
}

export const MIGRATION_SOURCE_DOCUMENTATION: Partial<Record<MigrationBiSourceTool, MigrationSourceDocumentationReference[]>> = {
  domo: [
    {
      title: 'Domo API overview',
      url: 'https://www.domo.com/docs/portal/API-Reference/overview',
      authority: 'Domo documentation',
      artifactClasses: ['authentication', 'dataset', 'card', 'page', 'API scope'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Domo Product Search API',
      url: 'https://www.domo.com/docs/api-reference/search-product-api/query',
      authority: 'Domo documentation',
      artifactClasses: ['dataset discovery', 'card discovery', 'page discovery', 'dependency handoff discovery'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Domo DataSet metadata API',
      url: 'https://www.domo.com/docs/api-reference/datasets-api/get-metadata',
      authority: 'Domo documentation',
      artifactClasses: ['dataset', 'metadata', 'owner', 'refresh state'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Domo DataSet schema API',
      url: 'https://www.domo.com/docs/api-reference/dataset-schema-api/return-the-schema-for-a-specified-dataset',
      authority: 'Domo documentation',
      artifactClasses: ['dataset schema', 'field', 'data type'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Domo DataSet access list API',
      url: 'https://www.domo.com/docs/api-reference/datasets-api/dataset-access-list',
      authority: 'Domo documentation',
      artifactClasses: ['dataset access', 'user', 'group', 'permission'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Domo DataSet Card membership API',
      url: 'https://www.domo.com/docs/api-reference/datasets-api/get-cards-for-dataset',
      authority: 'Domo documentation',
      artifactClasses: ['dataset binding', 'card membership', 'drill discovery'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Domo Page Card membership example (PDF Export tutorial)',
      url: 'https://www.domo.com/docs/portal/Apps/Pro-Code-Editor/Tutorials/pdf-export',
      authority: 'Domo official tutorial (Preview discovery only; not a formal API reference)',
      artifactClasses: ['page discovery', 'card membership', 'Preview evidence'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Domo Beast Mode search API',
      url: 'https://www.domo.com/docs/api-reference/beast-modes/get-all-beast-modes',
      authority: 'Domo documentation',
      artifactClasses: ['Beast Mode discovery', 'calculation linkage', 'pagination'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Domo Beast Mode detail API',
      url: 'https://www.domo.com/docs/api-reference/beast-modes/get-beast-mode-by-id',
      authority: 'Domo documentation',
      artifactClasses: ['Beast Mode', 'calculation expression', 'dataset binding', 'card binding'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Beast Mode FIXED Functions',
      url: 'https://www.domo.com/docs/s/article/4408174643607',
      authority: 'Domo documentation',
      artifactClasses: ['Beast Mode', 'FIXED level of detail', 'filter behavior'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Variables overview',
      url: 'https://www.domo.com/docs/s/article/7903767835031',
      authority: 'Domo documentation',
      artifactClasses: ['Variable', 'default value', 'Beast Mode dependency', 'dashboard control'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Get Chart Card Definition',
      url: 'https://www.domo.com/docs/portal/42d54af2095ac-get-chart-card-definition',
      authority: 'Domo Platform API documentation (OAuth)',
      artifactClasses: ['Analyzer query', 'chart type', 'field binding', 'filter', 'calculated field', 'quick filter'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Get Drill Properties',
      url: 'https://www.domo.com/docs/portal/0945428d284ab-get-drill-properties',
      authority: 'Domo Platform API documentation (OAuth)',
      artifactClasses: ['Card drill path', 'drill order'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Create a SQL DataFlow',
      url: 'https://www.domo.com/docs/s/article/360042922994',
      authority: 'Domo documentation',
      artifactClasses: ['SQL DataFlow', 'transform', 'input dataset', 'output dataset'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Magic ETL Tiles: Combine Data',
      url: 'https://www.domo.com/docs/s/article/360044876194',
      authority: 'Domo documentation',
      artifactClasses: ['Magic ETL', 'relationship', 'join', 'join key', 'join type', 'cardinality'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Optimizing a SQL DataFlow',
      url: 'https://www.domo.com/docs/s/article/360042923014',
      authority: 'Domo documentation',
      artifactClasses: ['SQL DataFlow', 'JOIN predicate', 'input relationship trace', 'query-view candidate'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Magic ETL',
      url: 'https://www.domo.com/docs/s/topic/0TO5w000000ZanvGAC/magic-etl',
      authority: 'Domo documentation',
      artifactClasses: ['Magic ETL', 'tile graph', 'input dataset', 'output dataset', 'data-engineering handoff'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Personalized Data Permissions',
      url: 'https://www.domo.com/docs/s/article/360042934614',
      authority: 'Domo product documentation and Platform API guidance (OAuth)',
      artifactClasses: ['PDP policy', 'row policy', 'column policy', 'user and group assignment'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Page Filters and Filter Views on Dashboards',
      url: 'https://www.domo.com/docs/s/article/360042923914?language=en_US',
      authority: 'Domo documentation',
      artifactClasses: ['Page filter', 'Filter View', 'Card interaction', 'dashboard control'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Domo Workflows API',
      url: 'https://www.domo.com/docs/portal/API-Reference/Product-APIs/Workflows',
      authority: 'Domo documentation',
      artifactClasses: ['workflow operation', 'workflow permission', 'redesign handoff'],
      reviewedAt: '2026-08-05',
    },
  ],
  looker: [
    {
      title: 'Looker API login',
      url: 'https://cloud.google.com/looker/docs/reference/looker-api/latest/methods/ApiAuth/login',
      authority: 'Google Cloud Looker API documentation',
      artifactClasses: ['authentication', 'API client credentials', 'short-lived API token'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Get compiled LookML model Explore',
      url: 'https://cloud.google.com/looker/docs/reference/looker-api/latest/methods/LookmlModel/lookml_model_explore',
      authority: 'Google Cloud Looker API documentation',
      artifactClasses: ['compiled definition', 'semantic model', 'Explore', 'view', 'field', 'measure', 'relationship', 'filter'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Get dashboard definition',
      url: 'https://cloud.google.com/looker/docs/reference/looker-api/latest/methods/Dashboard/dashboard',
      authority: 'Google Cloud Looker API documentation',
      artifactClasses: ['compiled definition', 'dashboard', 'query', 'tile', 'filter', 'layout metadata'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Get Look definition',
      url: 'https://cloud.google.com/looker/docs/reference/looker-api/latest/methods/Look/look',
      authority: 'Google Cloud Looker API documentation',
      artifactClasses: ['compiled definition', 'Look', 'query', 'field', 'filter', 'sort', 'pivot', 'visualization metadata'],
      reviewedAt: '2026-08-13',
    },
    {
      title: 'Search dashboards',
      url: 'https://docs.cloud.google.com/looker/docs/reference/looker-api/latest/methods/Dashboard/search_dashboards',
      authority: 'Google Cloud Looker API documentation',
      artifactClasses: ['dashboard discovery', 'bounded pagination', 'stable source ID'],
      reviewedAt: '2026-08-13',
    },
    {
      title: 'Search Looks',
      url: 'https://docs.cloud.google.com/looker/docs/reference/looker-api/latest/methods/Look/search_looks',
      authority: 'Google Cloud Looker API documentation',
      artifactClasses: ['Look discovery', 'bounded pagination', 'stable source ID'],
      reviewedAt: '2026-08-13',
    },
    {
      title: 'Looker API authentication',
      url: 'https://docs.cloud.google.com/looker/docs/api-auth',
      authority: 'Google Cloud Looker documentation',
      artifactClasses: ['authentication', 'API scope', 'service account'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Looker API reference',
      url: 'https://docs.cloud.google.com/looker/docs/reference/looker-api/latest',
      authority: 'Google Cloud Looker documentation',
      artifactClasses: ['dashboard', 'query', 'LookML model', 'folder', 'schedule'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Looker access_filter',
      url: 'https://docs.cloud.google.com/looker/docs/reference/param-explore-access-filter',
      authority: 'Google Cloud Looker documentation',
      artifactClasses: ['access filter', 'user attribute', 'row-level security'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Looker derived table methods',
      url: 'https://docs.cloud.google.com/looker/docs/reference/looker-api/latest/methods/DerivedTable',
      authority: 'Google Cloud Looker documentation',
      artifactClasses: ['PDT', 'derived table', 'dependency graph'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'LookML refinements',
      url: 'https://docs.cloud.google.com/looker/docs/lookml-refinements',
      authority: 'Google Cloud Looker documentation',
      artifactClasses: ['view refinement', 'Explore refinement', 'include order', 'dependency graph'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'LookML include parameter',
      url: 'https://docs.cloud.google.com/looker/docs/reference/param-model-include',
      authority: 'Google Cloud Looker documentation',
      artifactClasses: ['include', 'project dependency', 'view', 'Explore'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'LookML measure parameter',
      url: 'https://docs.cloud.google.com/looker/docs/reference/param-field-measure',
      authority: 'Google Cloud Looker documentation',
      artifactClasses: ['measure', 'metric', 'aggregate calculation'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'LookML join parameter',
      url: 'https://docs.cloud.google.com/looker/docs/reference/param-explore-join',
      authority: 'Google Cloud Looker documentation',
      artifactClasses: ['join', 'relationship', 'cardinality', 'sql_on'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'LookML access grants',
      url: 'https://docs.cloud.google.com/looker/docs/reference/param-model-access-grant',
      authority: 'Google Cloud Looker documentation',
      artifactClasses: ['access grant', 'permission', 'user attribute', 'governance'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Building LookML dashboards',
      url: 'https://docs.cloud.google.com/looker/docs/building-lookml-dashboards',
      authority: 'Google Cloud Looker documentation',
      artifactClasses: ['dashboard', 'tile', 'visual', 'filter', 'layout'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Looker to Omni migration skill',
      url: 'https://docs.omni.co/guides/migrations/looker-to-omni-skill',
      authority: 'Omni documentation',
      artifactClasses: ['LookML', 'Omni model', 'migration validation'],
      reviewedAt: '2026-08-05',
    },
  ],
  metabase: [
    {
      title: 'Metabase API documentation',
      url: 'https://www.metabase.com/docs/latest/api-documentation',
      authority: 'Metabase documentation',
      artifactClasses: ['API contract', 'discovery metadata', 'database', 'table', 'field', 'segment', 'question', 'dashboard', 'filter', 'collection', 'permission graph', 'notification'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Metabase API keys',
      url: 'https://www.metabase.com/docs/latest/people-and-groups/api-keys',
      authority: 'Metabase documentation',
      artifactClasses: ['authentication', 'API key', 'group permissions'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Metabase serialization',
      url: 'https://www.metabase.com/docs/latest/installation-and-operation/serialization',
      authority: 'Metabase documentation',
      artifactClasses: ['authoritative definition', 'serialization', 'database', 'table', 'field', 'segment', 'question', 'dashboard', 'collection'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Metabase API changelog',
      url: 'https://www.metabase.com/docs/latest/developers-guide/api-changelog',
      authority: 'Metabase documentation',
      artifactClasses: ['API compatibility', 'MBQL version', 'removed endpoint'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Metabase dashboard filters and parameters',
      url: 'https://www.metabase.com/docs/latest/dashboards/filters',
      authority: 'Metabase documentation',
      artifactClasses: ['dashboard filter', 'parameter', 'card mapping'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Metabase collection permissions',
      url: 'https://www.metabase.com/docs/latest/permissions/collections',
      authority: 'Metabase documentation',
      artifactClasses: ['collection', 'permission', 'governance handoff'],
      reviewedAt: '2026-08-05',
    },
  ],
  webfocus: [
    {
      title: 'WebFOCUS RESTful Web Services 9.3.0',
      url: 'https://docs.tibco.com/pub/wf-wf/9.3.0/doc/html/ibi_help_voyager_server/rs/RESTful_Web_Services.htm',
      authority: 'TIBCO WebFOCUS documentation',
      artifactClasses: ['authentication session', 'repository discovery', 'repository content', 'FEX', 'MAS', 'ACX', 'schedule metadata'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'WebFOCUS Master File introduction 8.2.07',
      url: 'https://docs.tibco.com/webfocus/8207/doc/html/topic/com.ibi.help.syn/source/intro.htm',
      authority: 'TIBCO WebFOCUS documentation',
      artifactClasses: ['authoritative definition', 'Master File', 'segment', 'field', 'alias', 'data type', 'relationship'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'WebFOCUS Change Management 8.2.07',
      url: 'https://docs.tibco.com/webfocus/8207/doc/html/topic/com.ibi.help.portal/source/change_management.htm',
      authority: 'TIBCO WebFOCUS documentation',
      artifactClasses: ['manual required', 'Change Management package', 'portal content', 'repository dependency closure'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'WebFOCUS RESTful Web Services',
      url: 'https://docs.tibco.com/pub/wf-wf/9.3.3/doc/html/embedded-bi-user/02REST_WS16.htm',
      authority: 'TIBCO WebFOCUS documentation',
      artifactClasses: ['repository', 'report procedure', 'parameters', 'schedule and library metadata'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'WebFOCUS Master File syntax',
      url: 'https://docs.tibco.com/pub/wf-wf/9.3.4/doc/html/describing-data-lang/ids17.htm',
      authority: 'TIBCO WebFOCUS documentation',
      artifactClasses: ['Master File', 'segment', 'field', 'alias', 'data type'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'WebFOCUS JOIN command',
      url: 'https://docs.tibco.com/pub/wf-wf/9.3.4/doc/html/describing-data-lang/join85.htm',
      authority: 'TIBCO WebFOCUS documentation',
      artifactClasses: ['join', 'relationship', 'cardinality evidence'],
      reviewedAt: '2026-08-05',
    },
  ],
  microstrategy: [
    {
      title: 'Strategy REST API authentication',
      url: 'https://microstrategy.github.io/rest-api-docs/getting-started/authentication/',
      authority: 'Strategy REST API documentation',
      artifactClasses: ['authentication', 'server session', 'project-bound session'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Strategy project management workflow',
      url: 'https://microstrategy.github.io/rest-api-docs/common-workflows/analytics/project-management/',
      authority: 'Strategy REST API documentation',
      artifactClasses: ['project', 'discovery metadata', 'project binding'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Retrieve a report definition',
      url: 'https://microstrategy.github.io/rest-api-docs/common-workflows/analytics/manage-reports/manage-report-objects/retrieve-a-reports-definition/',
      authority: 'Strategy REST API documentation',
      artifactClasses: ['authoritative definition', 'report', 'dataset', 'attribute', 'metric', 'filter', 'prompt'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Apply filters to a dossier',
      url: 'https://microstrategy.github.io/rest-api-docs/common-workflows/analytics/filter-data/filter-dossier-instances/apply-filters-to-a-dossier/',
      authority: 'Strategy REST API documentation',
      artifactClasses: ['dossier filter context', 'selector hierarchy', 'dataset context', 'filter', 'prompt', 'manual layout boundary'],
      reviewedAt: '2026-08-13',
    },
    {
      title: 'Retrieve a metric definition',
      url: 'https://microstrategy.github.io/rest-api-docs/common-workflows/modeling/manage-metric-objects/retrieve-a-metrics-definition/',
      authority: 'Strategy REST API documentation',
      artifactClasses: ['authoritative definition', 'metric', 'calculation', 'format', 'dependency'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Retrieve a filter definition',
      url: 'https://microstrategy.github.io/rest-api-docs/common-workflows/modeling/manage-filter-objects/retrieve-a-filters-definition/',
      authority: 'Strategy REST API documentation',
      artifactClasses: ['authoritative definition', 'filter', 'qualification', 'security filter dependency'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'View report and document details',
      url: 'https://www2.microstrategy.com/producthelp/current/MSTRWeb/WebHelp/Lang_1033/Content/View_report_details.htm',
      authority: 'Strategy product documentation',
      artifactClasses: ['report', 'document', 'attributes', 'metrics', 'filters', 'SQL', 'execution evidence'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Accessing data in a document: The dataset',
      url: 'https://www2.microstrategy.com/producthelp/Current/ReportDesigner/WebHelp/Lang_1033/Content/Accessing_data_in_a_document__The_dataset_report.htm',
      authority: 'Strategy product documentation',
      artifactClasses: ['dataset report', 'Intelligent Cube', 'document dependency'],
      reviewedAt: '2026-08-05',
    },
  ],
  tableau: [
    {
      title: 'Tableau REST API authentication',
      url: 'https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_auth.htm',
      authority: 'Tableau documentation',
      artifactClasses: ['authentication', 'personal access token', 'site session'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Tableau workbook and view methods',
      url: 'https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_workbooks_and_views.htm',
      authority: 'Tableau REST API documentation',
      artifactClasses: ['authoritative definition', 'workbook', 'TWB', 'TWBX', 'worksheet', 'dashboard', 'view', 'connection'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Tableau data source methods',
      url: 'https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_data_sources.htm',
      authority: 'Tableau REST API documentation',
      artifactClasses: ['authoritative definition', 'data source', 'TDS', 'TDSX', 'connection', 'field'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Tableau permissions methods',
      url: 'https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_permissions.htm',
      authority: 'Tableau REST API documentation',
      artifactClasses: ['governance evidence', 'permission', 'capability', 'user', 'group'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Tableau extract and encryption methods',
      url: 'https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_extract_and_encryption.htm',
      authority: 'Tableau REST API documentation',
      artifactClasses: ['governance evidence', 'extract refresh task', 'schedule', 'encryption state'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Tableau subscription methods',
      url: 'https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_subscriptions.htm',
      authority: 'Tableau REST API documentation',
      artifactClasses: ['governance evidence', 'subscription', 'delivery schedule', 'recipient handoff'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Get started with Tableau Metadata API',
      url: 'https://help.tableau.com/current/api/metadata_api/en-us/docs/meta_api_start.html',
      authority: 'Tableau Metadata API documentation',
      artifactClasses: ['governance evidence', 'workbook', 'data source', 'calculated field', 'lineage', 'upstream table', 'downstream dependency'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Tableau Metadata API',
      url: 'https://help.tableau.com/current/api/metadata_api/en-us/',
      authority: 'Tableau documentation',
      artifactClasses: ['workbook', 'data source', 'field', 'lineage', 'external asset'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Tableau REST API publishing resources',
      url: 'https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_publish.htm',
      authority: 'Tableau documentation',
      artifactClasses: ['TWB', 'TWBX', 'TDS', 'TDSX', 'extract resource'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Tableau calculation functions',
      url: 'https://help.tableau.com/current/pro/desktop/en-us/functions_all_categories.htm',
      authority: 'Tableau documentation',
      artifactClasses: ['calculated field', 'aggregate calculation', 'table calculation', 'LOD expression'],
      reviewedAt: '2026-08-05',
    },
  ],
  power_bi: [
    {
      title: 'Microsoft Fabric REST API service root',
      url: 'https://api.fabric.microsoft.com/v1',
      authority: 'Microsoft Fabric service endpoint',
      artifactClasses: ['API endpoint', 'workspace', 'item discovery', 'definition retrieval'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Power BI REST API service root',
      url: 'https://api.powerbi.com/v1.0/myorg',
      authority: 'Microsoft Power BI service endpoint',
      artifactClasses: ['API endpoint', 'workspace governance', 'semantic model permission', 'refresh schedule'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Microsoft identity platform authority root',
      url: 'https://login.microsoftonline.com',
      authority: 'Microsoft identity platform endpoint',
      artifactClasses: ['authentication endpoint', 'tenant authority', 'OAuth client credentials'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Microsoft Fabric API default scope',
      url: 'https://api.fabric.microsoft.com/.default',
      authority: 'Microsoft identity platform resource scope',
      artifactClasses: ['OAuth scope', 'Fabric item discovery', 'definition retrieval'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Power BI API default scope',
      url: 'https://analysis.windows.net/powerbi/api/.default',
      authority: 'Microsoft identity platform resource scope',
      artifactClasses: ['OAuth scope', 'Power BI workspace governance', 'semantic model permission', 'refresh schedule'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Fabric list items',
      url: 'https://learn.microsoft.com/en-us/rest/api/fabric/core/items/list-items',
      authority: 'Microsoft Learn Fabric REST API documentation',
      artifactClasses: ['discovery metadata', 'workspace', 'semantic model', 'report', 'item identity'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Get Fabric semantic model definition',
      url: 'https://learn.microsoft.com/en-us/rest/api/fabric/semanticmodel/items/get-semantic-model-definition',
      authority: 'Microsoft Learn Fabric REST API documentation',
      artifactClasses: ['authoritative definition', 'semantic model', 'TMDL', 'TMSL', 'table', 'field', 'measure', 'relationship', 'role'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Get Fabric report definition',
      url: 'https://learn.microsoft.com/en-us/rest/api/fabric/report/items/get-report-definition',
      authority: 'Microsoft Learn Fabric REST API documentation',
      artifactClasses: ['authoritative definition', 'report', 'PBIR', 'PBIR-Legacy', 'page', 'visual', 'filter', 'bookmark'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Fabric long-running operations',
      url: 'https://learn.microsoft.com/en-us/rest/api/fabric/articles/long-running-operation',
      authority: 'Microsoft Learn Fabric REST API documentation',
      artifactClasses: ['definition retrieval operation', 'operation status', 'result location', 'retry timing'],
      reviewedAt: '2026-08-13',
    },
    {
      title: 'Get Fabric operation state',
      url: 'https://learn.microsoft.com/en-us/rest/api/fabric/core/long-running-operations/get-operation-state',
      authority: 'Microsoft Learn Fabric REST API documentation',
      artifactClasses: ['definition retrieval operation', 'operation status', 'Location header', 'result location'],
      reviewedAt: '2026-08-13',
    },
    {
      title: 'Get Fabric operation result',
      url: 'https://learn.microsoft.com/en-us/rest/api/fabric/core/long-running-operations/get-operation-result',
      authority: 'Microsoft Learn Fabric REST API documentation',
      artifactClasses: ['definition retrieval operation', 'operation result', 'definition payload'],
      reviewedAt: '2026-08-13',
    },
    {
      title: 'Fabric report definition format',
      url: 'https://learn.microsoft.com/en-us/rest/api/fabric/articles/item-management/definitions/report-definition',
      authority: 'Microsoft Learn Fabric REST API documentation',
      artifactClasses: ['report definition', 'PBIR', 'PBIR-Legacy', 'definition part', 'behavioral review boundary'],
      reviewedAt: '2026-08-13',
    },
    {
      title: 'Get Power BI reports in a workspace',
      url: 'https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-reports-in-group',
      authority: 'Microsoft Learn Power BI REST API documentation',
      artifactClasses: ['governance evidence', 'workspace', 'report', 'semantic model binding'],
      reviewedAt: '2026-08-13',
    },
    {
      title: 'Power BI get group users',
      url: 'https://learn.microsoft.com/en-us/rest/api/power-bi/groups/get-group-users',
      authority: 'Microsoft Learn Power BI REST API documentation',
      artifactClasses: ['governance evidence', 'workspace', 'user', 'group', 'role'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Power BI get dataset users in group',
      url: 'https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/get-dataset-users-in-group',
      authority: 'Microsoft Learn Power BI REST API documentation',
      artifactClasses: ['governance evidence', 'semantic model', 'user', 'permission'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Power BI get refresh schedule in group',
      url: 'https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/get-refresh-schedule-in-group',
      authority: 'Microsoft Learn Power BI REST API documentation',
      artifactClasses: ['governance evidence', 'semantic model', 'refresh schedule', 'operational handoff'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Power BI service principal access',
      url: 'https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-service-principal',
      authority: 'Microsoft Learn Power BI documentation',
      artifactClasses: ['authentication', 'service principal', 'tenant setting', 'workspace access'],
      reviewedAt: '2026-08-12',
    },
    {
      title: 'Power BI REST APIs',
      url: 'https://learn.microsoft.com/en-us/rest/api/power-bi/',
      authority: 'Microsoft Learn',
      artifactClasses: ['workspace', 'semantic model', 'report', 'dashboard', 'administration'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Power BI Desktop project semantic model folder',
      url: 'https://learn.microsoft.com/en-us/power-bi/developer/projects/projects-dataset',
      authority: 'Microsoft Learn',
      artifactClasses: ['PBIP', 'TMDL', 'semantic model definition', 'table', 'field', 'measure', 'relationship'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Power BI Desktop project report folder',
      url: 'https://learn.microsoft.com/en-us/power-bi/developer/projects/projects-report',
      authority: 'Microsoft Learn',
      artifactClasses: ['PBIR', 'report', 'page', 'visual', 'filter', 'bookmark'],
      reviewedAt: '2026-08-05',
    },
  ],
  sigma: [
    {
      title: 'Sigma API token exchange',
      url: 'https://help.sigmacomputing.com/reference/post-token',
      authority: 'Sigma API documentation',
      artifactClasses: ['authentication', 'API client credentials', 'short-lived access token'],
      reviewedAt: '2026-08-13',
    },
    {
      title: 'Get Sigma Data Model specification',
      url: 'https://help.sigmacomputing.com/reference/get-data-model-spec',
      authority: 'Sigma API documentation',
      artifactClasses: ['authoritative definition', 'data model', 'view', 'field', 'metric', 'relationship', 'source', 'lineage'],
      reviewedAt: '2026-08-13',
    },
    {
      title: 'Get Sigma workbook',
      url: 'https://help.sigmacomputing.com/reference/get-workbook',
      authority: 'Sigma API documentation',
      artifactClasses: ['compiled definition', 'workbook content evidence', 'page', 'element', 'query', 'control', 'lineage', 'grant', 'schedule'],
      reviewedAt: '2026-08-13',
    },
    {
      title: 'About the Sigma REST API',
      url: 'https://help.sigmacomputing.com/docs/get-started-with-sigmas-api',
      authority: 'Sigma documentation',
      artifactClasses: ['authentication', 'workbook', 'dataset', 'team', 'connection'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'List elements in a workbook',
      url: 'https://help.sigmacomputing.com/reference/list-workbook-elements',
      authority: 'Sigma documentation',
      artifactClasses: ['workbook', 'page', 'element', 'control', 'pagination'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Data model representation with a metric',
      url: 'https://help.sigmacomputing.com/docs/example-representation-data-model-with-a-table-and-a-metric',
      authority: 'Sigma documentation',
      artifactClasses: ['data model', 'table element', 'metric', 'column identity'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Data model representation with a relationship',
      url: 'https://help.sigmacomputing.com/docs/example-representation-data-model-with-a-table-and-a-relationship',
      authority: 'Sigma documentation',
      artifactClasses: ['data model', 'table element', 'relationship', 'join key'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'List materialization schedules for a data model',
      url: 'https://help.sigmacomputing.com/reference/list-data-model-materialization-schedules',
      authority: 'Sigma documentation',
      artifactClasses: ['materialization', 'schedule', 'pagination'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Add version tags to workbooks and data models',
      url: 'https://help.sigmacomputing.com/docs/add-version-tags-to-workbooks-and-data-models',
      authority: 'Sigma documentation',
      artifactClasses: ['workbook version', 'data model version', 'source pin'],
      reviewedAt: '2026-08-05',
    },
    {
      title: 'Sigma basics',
      url: 'https://help.sigmacomputing.com/docs/sigma-basics',
      authority: 'Sigma documentation',
      artifactClasses: ['data model', 'dataset', 'workbook', 'element dependency'],
      reviewedAt: '2026-08-05',
    },
  ],
};

export function migrationSourceDocumentation(source: MigrationBiSourceTool): MigrationSourceDocumentationReference[] {
  return (MIGRATION_SOURCE_DOCUMENTATION[source] || []).map((reference) => ({
    ...reference,
    artifactClasses: [...reference.artifactClasses],
  }));
}
