import type {
  TransformationOperation,
  TransformationPackage,
  TransformationPackageFile,
  TransformationTargetAdapterCapability,
  TransformationTargetKind,
} from './types';
import { transformationPackageFileChecksum } from './transformationPackage';

export const TRANSFORMATION_TARGET_CAPABILITIES: Record<TransformationTargetKind, TransformationTargetAdapterCapability> = {
  generic_sql: {
    target: 'generic_sql',
    label: 'Generic SQL',
    supportsExport: true,
    supportsDeployment: false,
    supportsRollbackAutomation: false,
    supportedMaterializations: ['view', 'table'],
    limitations: ['Dialect-specific functions require review.', 'Incremental merge logic is exported as a handoff.'],
  },
  dbt: {
    target: 'dbt',
    label: 'dbt project',
    supportsExport: true,
    supportsDeployment: false,
    supportsRollbackAutomation: false,
    supportedMaterializations: ['view', 'table', 'incremental'],
    limitations: ['OmniKit exports project files but does not invoke dbt Cloud or dbt Core.'],
  },
  snowflake: {
    target: 'snowflake',
    label: 'Snowflake SQL',
    supportsExport: true,
    supportsDeployment: true,
    supportsRollbackAutomation: false,
    supportedMaterializations: ['view', 'table'],
    limitations: ['Deployment requires a separately approved Snowflake connection and non-production target.', 'Incremental keys require explicit design review.'],
  },
  databricks: {
    target: 'databricks',
    label: 'Databricks SQL',
    supportsExport: true,
    supportsDeployment: true,
    supportsRollbackAutomation: false,
    supportedMaterializations: ['view', 'table'],
    limitations: ['Deployment requires an approved SQL warehouse and non-production catalog/schema.', 'Incremental keys require explicit design review.'],
  },
  motherduck: {
    target: 'motherduck',
    label: 'MotherDuck SQL',
    supportsExport: true,
    supportsDeployment: false,
    supportsRollbackAutomation: false,
    supportedMaterializations: ['view', 'table'],
    limitations: ['OmniKit exports DuckDB-compatible SQL; execution remains operator-owned.', 'Incremental keys require explicit design review.'],
  },
};

function sqlHeader(target: TransformationTargetKind, operation: TransformationOperation): string {
  return [
    '-- Generated by OmniKit BI Migration Studio',
    `-- Target: ${target}`,
    `-- Operation: ${operation.id}`,
    `-- Idempotency key: ${operation.idempotencyKey}`,
    '-- Review and validate in a development environment before promotion.',
  ].join('\n');
}

function renderedSql(target: TransformationTargetKind, operation: TransformationOperation): string {
  const header = sqlHeader(target, operation);
  if (operation.materialization === 'incremental') {
    return `${header}\n-- BLOCKED FOR DIRECT EXECUTION: define a unique key and incremental strategy.\n${operation.sql};\n`;
  }
  const objectKind = operation.materialization === 'table' ? 'TABLE' : 'VIEW';
  return `${header}\nCREATE ${objectKind} IF NOT EXISTS ${operation.name} AS\n${operation.sql};\n`;
}

function yamlScalar(value: string): string {
  return JSON.stringify(value);
}

function dbtModelSql(operation: TransformationOperation): string {
  const materialized = operation.materialization === 'incremental' ? 'incremental' : operation.materialization;
  return `{{ config(materialized=${JSON.stringify(materialized)}) }}\n\n${operation.sql}\n`;
}

function dbtSchemaYaml(operations: TransformationOperation[]): string {
  const models = operations.map((operation) => [
    `  - name: ${yamlScalar(operation.name)}`,
    `    description: ${yamlScalar(`Migrated from ${operation.nodeId}. Review before promotion.`)}`,
    '    meta:',
    `      omnikit_operation_id: ${yamlScalar(operation.id)}`,
    `      omnikit_idempotency_key: ${yamlScalar(operation.idempotencyKey)}`,
  ].join('\n')).join('\n');
  return `version: 2\nmodels:\n${models || '  []'}\n`;
}

async function makeFile(
  file: Omit<TransformationPackageFile, 'sha256'>,
): Promise<TransformationPackageFile> {
  return { ...file, sha256: await transformationPackageFileChecksum(file.content) };
}

async function manifestFile(pkg: TransformationPackage, executionOrder: number): Promise<TransformationPackageFile> {
  const content = `${JSON.stringify({
    schemaVersion: pkg.schemaVersion,
    packageId: pkg.packageId,
    sourcePlatform: pkg.sourcePlatform,
    target: pkg.target,
    operations: pkg.operations.map((operation) => ({
      id: operation.id,
      name: operation.name,
      kind: operation.kind,
      dependencies: operation.dependencies,
      materialization: operation.materialization,
      idempotencyKey: operation.idempotencyKey,
    })),
    handoffs: pkg.handoffs,
    validationQueries: pkg.validationQueries,
    rollbackInstructions: pkg.rollbackInstructions,
  }, null, 2)}\n`;
  return makeFile({
    id: 'file:manifest',
    path: 'omnikit-manifest.json',
    content,
    mediaType: 'application/json',
    executionOrder,
    operationIds: pkg.operations.map((operation) => operation.id),
  });
}

export async function renderTransformationPackage(
  pkg: TransformationPackage,
  target: TransformationTargetKind = pkg.target,
): Promise<TransformationPackage> {
  const capabilities = TRANSFORMATION_TARGET_CAPABILITIES[target];
  if (!capabilities.supportsExport) throw new Error(`${capabilities.label} does not support package export.`);
  const files: TransformationPackageFile[] = [];
  if (target === 'dbt') {
    for (const [index, operation] of pkg.operations.entries()) {
      files.push(await makeFile({
        id: `file:${operation.id}`,
        path: `models/${operation.name}.sql`,
        content: dbtModelSql(operation),
        mediaType: 'text/sql',
        executionOrder: index,
        operationIds: [operation.id],
      }));
    }
    files.push(await makeFile({
      id: 'file:dbt-schema',
      path: 'models/schema.yml',
      content: dbtSchemaYaml(pkg.operations),
      mediaType: 'text/yaml',
      executionOrder: pkg.operations.length,
      operationIds: pkg.operations.map((operation) => operation.id),
    }));
  } else {
    for (const [index, operation] of pkg.operations.entries()) {
      files.push(await makeFile({
        id: `file:${operation.id}`,
        path: `transformations/${String(index + 1).padStart(3, '0')}_${operation.name}.sql`,
        content: renderedSql(target, operation),
        mediaType: 'text/sql',
        executionOrder: index,
        operationIds: [operation.id],
      }));
    }
  }
  files.push(await manifestFile({ ...pkg, target }, files.length));
  const unsupported = pkg.operations.filter((operation) => !capabilities.supportedMaterializations.includes(operation.materialization as 'view' | 'table' | 'incremental'));
  return {
    ...pkg,
    target,
    files,
    warnings: [
      ...pkg.warnings,
      ...unsupported.map((operation) => `${capabilities.label} cannot deploy ${operation.name} as ${operation.materialization}; export it for engineering review.`),
    ],
  };
}

export function transformationAdapterConformanceIssues(
  pkg: TransformationPackage,
  target: TransformationTargetKind = pkg.target,
): string[] {
  const capabilities = TRANSFORMATION_TARGET_CAPABILITIES[target];
  const issues: string[] = [];
  if (!capabilities.supportsExport) issues.push(`${capabilities.label} does not support export.`);
  pkg.operations.forEach((operation) => {
    if (!capabilities.supportedMaterializations.includes(operation.materialization as 'view' | 'table' | 'incremental')) {
      issues.push(`${operation.name} uses unsupported ${operation.materialization} materialization.`);
    }
  });
  pkg.files.forEach((file) => {
    if (!file.sha256) issues.push(`${file.path} is missing a checksum.`);
    if (file.path.startsWith('/') || file.path.includes('..')) issues.push(`${file.path} is not a safe relative path.`);
  });
  return issues;
}
