{
  "name": "Whataburger Semantic Model",
  "model": {
    "id": "pbi-model-whataburger",
    "name": "Whataburger Semantic Model",
    "culture": "en-US",
    "tables": [
      {
        "name": "Daily Grill Report",
        "columns": [
          { "name": "order_id", "dataType": "string" },
          { "name": "business_date", "dataType": "dateTime" },
          { "name": "store_number", "dataType": "string" },
          { "name": "order_channel", "dataType": "string" },
          { "name": "daypart", "dataType": "string" },
          { "name": "gross_sales", "dataType": "decimal" },
          { "name": "discounts", "dataType": "decimal" },
          { "name": "net_sales", "dataType": "decimal" },
          { "name": "order_count", "dataType": "int64" },
          { "name": "units_sold", "dataType": "int64" },
          { "name": "add_on_revenue", "dataType": "decimal" }
        ],
        "measures": [
          { "name": "total_revenue", "expression": "SUM('Daily Grill Report'[net_sales])" },
          { "name": "orders", "expression": "DISTINCTCOUNT('Daily Grill Report'[order_id])" },
          { "name": "average_bag_size", "expression": "DIVIDE([total_revenue], [orders])" },
          { "name": "attach_rate", "expression": "DIVIDE(SUM('Daily Grill Report'[add_on_revenue]), [total_revenue])" },
          { "name": "discount_rate", "expression": "DIVIDE(SUM('Daily Grill Report'[discounts]), SUM('Daily Grill Report'[gross_sales]))" }
        ]
      },
      {
        "name": "Whataburger Locations",
        "columns": [
          { "name": "store_number", "dataType": "string" },
          { "name": "location_name", "dataType": "string" },
          { "name": "city", "dataType": "string" },
          { "name": "state", "dataType": "string" },
          { "name": "territory", "dataType": "string" },
          { "name": "region", "dataType": "string" }
        ],
        "measures": [
          { "name": "location_count", "expression": "DISTINCTCOUNT('Whataburger Locations'[store_number])" }
        ]
      },
      {
        "name": "Bag Tickets",
        "columns": [
          { "name": "order_id", "dataType": "string" },
          { "name": "store_number", "dataType": "string" },
          { "name": "business_date", "dataType": "dateTime" },
          { "name": "item_count", "dataType": "int64" },
          { "name": "ticket_total", "dataType": "decimal" },
          { "name": "bag_size", "dataType": "string" },
          { "name": "order_channel", "dataType": "string" }
        ],
        "measures": [
          { "name": "items_per_bag", "expression": "DIVIDE(SUM('Bag Tickets'[item_count]), DISTINCTCOUNT('Bag Tickets'[order_id]))" }
        ]
      },
      {
        "name": "Grill Slips",
        "columns": [
          { "name": "order_id", "dataType": "string" },
          { "name": "menu_item_id", "dataType": "string" },
          { "name": "category", "dataType": "string" },
          { "name": "quantity", "dataType": "int64" },
          { "name": "line_revenue", "dataType": "decimal" },
          { "name": "station_name", "dataType": "string" },
          { "name": "prep_seconds", "dataType": "int64" }
        ],
        "measures": [
          { "name": "units_sold", "expression": "SUM('Grill Slips'[quantity])" }
        ]
      },
      {
        "name": "The Menu Board",
        "columns": [
          { "name": "menu_item_id", "dataType": "string" },
          { "name": "item_name", "dataType": "string" },
          { "name": "category", "dataType": "string" },
          { "name": "menu_group", "dataType": "string" },
          { "name": "list_price", "dataType": "decimal" },
          { "name": "active_flag", "dataType": "string" }
        ],
        "measures": [
          { "name": "active_menu_items", "expression": "CALCULATE(DISTINCTCOUNT('The Menu Board'[menu_item_id]), 'The Menu Board'[active_flag] = \"Y\")" }
        ]
      },
      {
        "name": "Menu Item P&L",
        "columns": [
          { "name": "menu_item_id", "dataType": "string" },
          { "name": "category", "dataType": "string" },
          { "name": "units_sold", "dataType": "int64" },
          { "name": "gross_revenue", "dataType": "decimal" },
          { "name": "discounts", "dataType": "decimal" },
          { "name": "net_revenue", "dataType": "decimal" },
          { "name": "food_cost", "dataType": "decimal" },
          { "name": "gross_margin", "dataType": "decimal" }
        ],
        "measures": [
          { "name": "total_gross_margin", "expression": "SUM('Menu Item P&L'[gross_margin])" },
          { "name": "margin_pct", "expression": "DIVIDE([total_gross_margin], SUM('Menu Item P&L'[net_revenue]))" },
          { "name": "total_food_cost", "expression": "SUM('Menu Item P&L'[food_cost])" }
        ]
      }
    ],
    "relationships": [
      { "name": "orders_locations", "fromTable": "Daily Grill Report", "fromColumn": "store_number", "toTable": "Whataburger Locations", "toColumn": "store_number", "fromCardinality": "many", "toCardinality": "one" },
      { "name": "orders_bags", "fromTable": "Daily Grill Report", "fromColumn": "order_id", "toTable": "Bag Tickets", "toColumn": "order_id", "fromCardinality": "one", "toCardinality": "one" },
      { "name": "orders_grill", "fromTable": "Daily Grill Report", "fromColumn": "order_id", "toTable": "Grill Slips", "toColumn": "order_id", "fromCardinality": "one", "toCardinality": "many" },
      { "name": "grill_menu", "fromTable": "Grill Slips", "fromColumn": "menu_item_id", "toTable": "The Menu Board", "toColumn": "menu_item_id", "fromCardinality": "many", "toCardinality": "one" },
      { "name": "grill_pnl", "fromTable": "Grill Slips", "fromColumn": "menu_item_id", "toTable": "Menu Item P&L", "toColumn": "menu_item_id", "fromCardinality": "many", "toCardinality": "one" }
    ],
    "roles": []
  }
}
